# Generated by Django 5.1.1 on 2024-09-27 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0002_alter_pet_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pet',
            name='group',
        ),
    ]
