# Generated by Django 5.1.1 on 2024-09-27 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0022_alter_pet_sex'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='sex',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Not Informed', 'Default')], default='Not Informed', max_length=20),
        ),
    ]
