# Generated by Django 5.1.1 on 2024-09-27 18:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0001_initial'),
        ('pets', '0003_remove_pet_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='pets',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pets', to='pets.pet'),
        ),
    ]
