# Generated by Django 5.1.1 on 2024-09-27 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0002_group_pets'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='pets',
        ),
    ]
